### ISSUE TITLE
Help: global access and VS2013.

### ISSUE THREAD

**Issue by starwing** [OldFisher/lua-api-pp#3]
Hi, I'm finding C++11 Lua wrapper library. I have found sol, selene and this library. but I found some diffcult to try this library:
  - how can I access global environment when I only have a lua::State? I just find get global in lua::Context, but it requires to call a functions (state.call), how can I just retrieve some informations without call a function? (I just use Lua as a configuation language in my project).
  - It seems can not compiles in VS2013, is there any plans to support it on Winodws?

**Comment by OldFisher** [comment]
Hello, thank you for your interest in this library.
- In order to access global state and all other library features, Context object is required. State object was designed only to offer basic lifetime control for Lua global state. Simplest (and intended) way to achieve your goal is to write a function doing the job and call it with State object. Short example:
```cpp
#include <iostream>
#include <luapp/lua.hpp>
using lua::Retval; using lua::Context; using lua::State;

static int answer = 0;

Retval readConfig(Context& c)  // Here we prepare the global state for use.
{
    answer = c.global["general"]["answer"];
    return c.ret();
}

void giveAnswer()
{
    std::cout << "The answer to the question of Life, Universe and Everything is ";
    std::cout << answer << std::endl;
}

int main()
{
    State s;
    s.runFile("config.lua");  // Load the configuration file
    s.call(mkcf<readConfig>);
    giveAnswer();
    return 0;
}
```
Alternatively, if you want to embed config-reading pieces into many functions, you can create a global Context object from the State and pass it as a parameter to your functions like this:
```cpp
#include <iostream>
#include <luapp/lua.hpp>
using lua::Context; using lua::State;

void giveAnswer(Context& c)
{
    std::cout << "The answer to the question of Life, Universe and Everything is ";
    std::cout << int(c.global["general"]["answer"]) << std::endl;
}

int main()
{
    State s;
    Context c(s.getRawState(), Context::initializeExplicitly);
    giveAnswer(c);
}
```
- this library was developed and tested on Windows, but with GCC compiler (MinGW suite) because Visual Studio 2013 offers only [limited support of C++11](https://msdn.microsoft.com/en-us/library/hh567368.aspx), missing some features this library depends on. Further versions of VS offer more complete support of the standard, but I'm not currently aware  at which version the compatibility is or will be attainable. Needless to say, any collaborators willing to test compatibility with newer versions of VS and other compilers are welcome.

**Comment by starwing** [comment]
Okay, I know that, but can we add some APIs to staete to make you can retrieve tables or values, etc without having a context? in my opinion context is using to maintain the stack index in a function all, but get a Table/value needn't change the stack index wherever you are.

**Comment by OldFisher** [comment]
Adding such API to State would actually mean duplicating it from the Context, which is not a good thing. It would lead to messy API, unnecessary code duplication, harder maintenance and tangled responsibilities.
The State object's purpose is to handle creation and destruction of Lua state, while Context's main purpose is to serve as a central access point to Lua functionality.
Stack state is actually maintained by value-related objects such as Value, Valset and especially temporaries. And by the way, simply reading a value from the table requires pushing the key on the stack (from which it gets popped during read operation) and therefore some stack management, not to mention nested tables, expressions and so on. For example, the expression `c.global["general"]["answer"]` generates 2 temporaries that produce this operation sequence:
- push string "general"
- push global table named `general`, discarding string "general" in process
- push string "answer"
- push value of `general.answer` discarding the string "answer"
- after the value is used, pop `general.answer`
- pop table `general`
As you can see, even if it's only reading, stack management is still required.

So, I recommend to use Context, because that's what it is designed for. There is no additional cost in doing so.
